version: '3.8'

services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot_container
    env_file: .env
    depends_on:
      - db
    networks:
      - botnet

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db_container
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - botnet
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  db_replica:
    build:
      context: ./db_repl
      dockerfile: Dockerfile
    container_name: db_replica_container
    env_file: .env
    depends_on:
      - db
    networks:
      - botnet
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      REPLICATOR_USER: ${DB_REPL_USER}
      REPLICATOR_PASSWORD: ${DB_REPL_PASSWORD}
      DB_HOST: ${DB_HOST}

networks:
  botnet:
    driver: bridge

volumes:
  db_data:
